# Generated by Django 6.0 on 2025-12-11 09:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "logo_url",
                    models.URLField(blank=True, help_text="URL логотипа компании"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "cover_image_url",
                    models.URLField(blank=True, help_text="Обложка мероприятия"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldOfStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Field of Study",
                "verbose_name_plural": "Fields of Study",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("partner", "Партнёр"),
                            ("admin", "Администратор"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VacancyInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "salary_min",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "salary_max",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("no", "Нет опыта"),
                            ("1-3", "1–3 года"),
                            ("3-5", "3–5 лет"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("high", "Среднее профессиональное"),
                            ("bachelor", "Бакалавриат"),
                            ("master", "Магистратура"),
                            ("student", "Студент"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full", "Полная занятость"),
                            ("part", "Частичная занятость"),
                            ("internship", "Стажировка"),
                            ("project", "Проектная работа"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("office", "Офис"),
                            ("remote", "Удалёнка"),
                            ("hybrid", "Гибрид"),
                            ("flexible", "Гибкий график"),
                            ("by_agreement", "По договорённости"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, help_text="HTML content"),
                ),
                (
                    "responsibilities",
                    models.TextField(blank=True, help_text="HTML content"),
                ),
                ("conditions", models.TextField(blank=True, help_text="HTML content")),
                ("city", models.CharField(blank=True, max_length=100)),
                ("address", models.CharField(blank=True, max_length=255)),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("internal", "Внутренний отклик"),
                            ("email", "Email"),
                            ("external_link", "Внешняя ссылка"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "response_destination",
                    models.CharField(
                        blank=True,
                        help_text="Email или URL при не-internal типе",
                        max_length=255,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="main.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_vacancies",
                        to="main.user",
                    ),
                ),
                (
                    "info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="main.vacancyinfo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume_file_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на PDF-резюме (если response_type = internal)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("reviewed", "Рассмотрено"),
                            ("invited", "Приглашён"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="main.user",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="main.vacancy",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "vacancy")},
            },
        ),
        migrations.CreateModel(
            name="VacancyField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to="main.fieldofstudy",
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="main.vacancy",
                    ),
                ),
            ],
            options={
                "unique_together": {("vacancy", "field")},
            },
        ),
    ]
