# Generated by Django 6.0 on 2025-12-15 20:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_alter_application_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
