# Generated by Django 6.0 on 2025-12-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_historicalcompany_historicalvacancy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalvacancy",
            name="schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Офис"),
                    ("remote", "Удалёнка"),
                    ("hybrid", "Гибрид"),
                    ("flexible", "Гибкий график"),
                    ("by_agreement", "По договорённости"),
                ],
                max_length=20,
                verbose_name="Тип занятости",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Офис"),
                    ("remote", "Удалёнка"),
                    ("hybrid", "Гибрид"),
                    ("flexible", "Гибкий график"),
                    ("by_agreement", "По договорённости"),
                ],
                max_length=20,
                verbose_name="Тип занятости",
            ),
        ),
    ]
