# Generated by Django 6.0 on 2025-12-15 20:37

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="application",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="application",
            name="user",
        ),
        migrations.RemoveField(
            model_name="application",
            name="vacancy",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.AlterUniqueTogether(
            name="vacancyfield",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="vacancyfield",
            name="field",
        ),
        migrations.RemoveField(
            model_name="vacancyfield",
            name="vacancy",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="info",
        ),
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Компания", "verbose_name_plural": "Компании"},
        ),
        migrations.AlterModelOptions(
            name="fieldofstudy",
            options={
                "verbose_name": "Направление подготовки",
                "verbose_name_plural": "Направления подготовки",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Вакансия",
                "verbose_name_plural": "Вакансии",
            },
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="company",
            name="logo_url",
        ),
        migrations.RemoveField(
            model_name="vacancy",
            name="created_by",
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos/", verbose_name="Логотип"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date joined"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(
                default=123, max_length=128, verbose_name="password"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="address",
            field=models.CharField(blank=True, max_length=255, verbose_name="Адрес"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="conditions",
            field=models.TextField(blank=True, verbose_name="Условия"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="description",
            field=models.TextField(default=123, verbose_name="Краткое описание"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "Полная занятость"),
                    ("part", "Частичная занятость"),
                    ("project", "Проектная работа"),
                ],
                max_length=20,
                verbose_name="Тип занятости",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "Нет опыта"),
                    ("1", "До 1 года"),
                    ("1-3", "1–3 года"),
                    ("3+", "Более 3 лет"),
                ],
                max_length=10,
                verbose_name="Опыт работы",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="field",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.fieldofstudy",
                verbose_name="Направление",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(blank=True, verbose_name="Требования"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="responsibilities",
            field=models.TextField(blank=True, verbose_name="Обязанности"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_max",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Зарплата до"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Зарплата от"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="schedule",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="График работы"
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="title",
            field=models.CharField(
                default=123, max_length=255, verbose_name="Название вакансии"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="company",
            name="industry",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Индустрия"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="fieldofstudy",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Название направления"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(max_length=255, verbose_name="Полное имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Администратор"),
                    ("partner", "Компания-партнер"),
                    ("student", "Студент"),
                ],
                max_length=20,
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="main.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.DeleteModel(
            name="Application",
        ),
        migrations.DeleteModel(
            name="VacancyField",
        ),
        migrations.DeleteModel(
            name="VacancyInfo",
        ),
    ]
