# Generated by Django 6.0 on 2025-12-12 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="logo_url",
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
        migrations.AlterField(
            model_name="vacancyinfo",
            name="city",
            field=models.CharField(max_length=100),
        ),
    ]
