# Generated by Django 6.0 on 2025-12-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_company_logo_url_company_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="logo",
            field=models.ImageField(
                blank=True, default="logos/not_found.png", null=True, upload_to="logos/"
            ),
        ),
    ]
