# Generated by Django 6.0 on 2025-12-12 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_company_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="main.company",
            ),
        ),
        migrations.AddField(
            model_name="vacancyinfo",
            name="field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="main.fieldofstudy",
            ),
        ),
        migrations.DeleteModel(
            name="VacancyField",
        ),
    ]
