# Generated by Django 6.0 on 2025-12-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_user_company_vacancyinfo_field_delete_vacancyfield"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="is_active",
        ),
        migrations.AddField(
            model_name="vacancyinfo",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
