# Generated by Django 6.0 on 2025-12-21 11:50

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_historicalvacancy_schedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("event_date", models.DateTimeField()),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, upload_to="events/", verbose_name="Обложка"
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="historicalvacancy",
            name="schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Офис"),
                    ("remote", "Удалёнка"),
                    ("hybrid", "Гибрид"),
                    ("flexible", "Гибкий график"),
                    ("by_agreement", "По договорённости"),
                ],
                max_length=20,
                verbose_name="График",
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Офис"),
                    ("remote", "Удалёнка"),
                    ("hybrid", "Гибрид"),
                    ("flexible", "Гибкий график"),
                    ("by_agreement", "По договорённости"),
                ],
                max_length=20,
                verbose_name="График",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalApplication",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "resume_file_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на PDF-резюме (если response_type = internal)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("reviewed", "Рассмотрено"),
                            ("invited", "Приглашён"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="main.vacancy",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical application",
                "verbose_name_plural": "historical applications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resume_file_url",
                    models.URLField(
                        blank=True,
                        help_text="Ссылка на PDF-резюме (если response_type = internal)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "На рассмотрении"),
                            ("reviewed", "Рассмотрено"),
                            ("invited", "Приглашён"),
                            ("rejected", "Отклонено"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="main.vacancy",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "vacancy")},
            },
        ),
    ]
