# Generated by Django 6.0 on 2025-12-15 19:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_user_options_user_date_joined_user_first_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="info",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="city",
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="conditions",
            field=models.TextField(blank=True, help_text="HTML content"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="description",
            field=models.TextField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="education_level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("high", "Среднее профессиональное"),
                    ("bachelor", "Бакалавриат"),
                    ("master", "Магистратура"),
                    ("student", "Студент"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="employment_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("full", "Полная занятость"),
                    ("part", "Частичная занятость"),
                    ("internship", "Стажировка"),
                    ("project", "Проектная работа"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="experience",
            field=models.CharField(
                blank=True,
                choices=[("no", "Нет опыта"), ("1-3", "1–3 года"), ("3-5", "3–5 лет")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="field",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacancies",
                to="main.fieldofstudy",
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="requirements",
            field=models.TextField(blank=True, help_text="HTML content"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="response_destination",
            field=models.CharField(
                blank=True,
                help_text="Email или URL при не-internal типе",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="response_type",
            field=models.CharField(
                choices=[
                    ("internal", "Внутренний отклик"),
                    ("email", "Email"),
                    ("external_link", "Внешняя ссылка"),
                ],
                default=123,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vacancy",
            name="responsibilities",
            field=models.TextField(blank=True, help_text="HTML content"),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_max",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="salary_min",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="schedule",
            field=models.CharField(
                blank=True,
                choices=[
                    ("office", "Офис"),
                    ("remote", "Удалёнка"),
                    ("hybrid", "Гибрид"),
                    ("flexible", "Гибкий график"),
                    ("by_agreement", "По договорённости"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vacancy",
            name="title",
            field=models.CharField(default=123, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="VacancyInfo",
        ),
    ]
